In [2]:
# 转换和对比鱼乐卡数据

import pandas as pd
from pandas import Series,DataFrame

# 宽表转长表
df = DataFrame(pd.read_excel('pos3_ylk.xlsx'))

df = df.pivot(index="finance_no",columns="variable",values="value")
df.to_excel('ylk_pos3_new.xls')
df

# 长表转宽表
df = DataFrame(pd.read_excel('ylk_pos4.xlsx'))

df = df.pivot(index="finance_no",columns="variable",values="value")
df.to_excel('ylk_pos4_new.xls')
df

variable,diamond,gold,platinum
finance_no,,,
0002,ylk_free_diamond_open,ylk_free_gold_close,ylk_free_platinum_open
0003,ylk_free_diamond_open,ylk_free_gold_close,ylk_free_platinum_close
0004,ylk_free_diamond_open,ylk_free_gold_close,ylk_free_platinum_close
0005,ylk_free_diamond_open,ylk_free_gold_close,ylk_free_platinum_close
0006,ylk_free_diamond_open,ylk_free_gold_close,ylk_free_platinum_close
...,...,...,...
9991,ylk_free_diamond_open,ylk_free_gold_close,ylk_free_platinum_close
M0001,ylk_free_diamond_open,ylk_free_gold_close,ylk_free_platinum_close
M0004,ylk_free_diamond_open,ylk_free_gold_close,ylk_free_platinum_close
T0001,ylk_free_diamond_open,ylk_free_gold_close,ylk_free_platinum_close
T0002,ylk_free_diamond_open,ylk_free_gold_close,ylk_free_platinum_close