In [3]:
# Pandas
import pandas as pd
from pandas import Series,DataFrame
import numpy as np

In [31]:
# Pandas 简介
# https://pandas.pydata.org/

In [32]:
np.random.randint(0,10,(4,4))

array([[9, 9, 0, 0],
       [9, 9, 9, 2],
       [8, 1, 4, 6],
       [3, 6, 5, 9]])

In [202]:
# 2. 初识DataFrame
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

# 使用二维数组index = [1,2,3,4], columns=['a','b','c','d']
# df1 = DataFrame(np.random.randint(0,10,(4,4)), index=[1,2,3,4], columns=['a','b','c','d'])
# print(df1)

# 使用字段创建（行索引由index决定，索引列由字典的键决定）
dict1 = {
    'Province': ['Guangdong','Beijing','Qinghai','Fujian'],
    'pop':[1.3,2.5,1.1,0.7],
    'year':[2018,2018,2018,2019]
}

df2 = pd.DataFrame(dict1) # index = [1,2,3,4]
print(df2)

# 将DataFrame转换成dict
# orient = 'list' 每一列的值以列表的形式承装
df2.to_dict(orient='list')

   a  b  c  d
1  7  1  1  2
2  5  2  0  5
3  1  8  3  5
4  8  5  4  4
    Province  pop  year
0  Guangdong  1.3  2018
1    Beijing  2.5  2018
2    Qinghai  1.1  2018
3     Fujian  0.7  2019

{'Province': ['Guangdong', 'Beijing', 'Qinghai', 'Fujian'],
 'pop': [1.3, 2.5, 1.1, 0.7],
 'year': [2018, 2018, 2018, 2019]}

In [46]:
# 3. 初识Series
dict1 = {
    'Province': ['Guangdong','Beijing','Qinghai','Fujian'],
    'pop':[1.3,2.5,1.1,0.7],
    'year':[2018,2018,2018,2019]
}
df2 = pd.DataFrame(dict1) # index = [1,2,3,4]
print(df2)

# 就是DataFrame
# series = df2['Province']
# print(series)
# print(type(series))

# 将列表转化成series index = ['a','b','c','d']
# sel = Series([1,2,3,4], index=['a','b','c','d'])
# print(sel)

# 将字典转换成Series
# dict = {'red':100,'black':400, 'green':300, 'pink':900}
# se3 = Series(dict)
# print(se3)

    Province  pop  year
0  Guangdong  1.3  2018
1    Beijing  2.5  2018
2    Qinghai  1.1  2018
3     Fujian  0.7  2019

In [48]:
# 4. 进阶认识DataFrame
df = pd.read_csv('./file/ratings.csv')
df

   userId  movieId  rating
0       1        1       4
1       1        3       4
2       1        6       4
3       1       47       5
4       1       50       5

In [80]:
# 5. Series数据获取
df = pd.read_csv('./file/ratings.csv')
# df

# 获取一列
series = df['movieId']

# 设置series的自定义索引
# series.index.tolist()
series.index = list('abcde')

print(series)

# print('索引下标:',series['c']) # 索引下标
# print('数值下标:',series[2]) # 数值下标
# print('位置下标:',series[2])

# 获取不连续的数
# print(series[['a','c']])
# print(series[[0,2]])

# 获取连续的数
# print(series['a':'c']) # 索引下标使用切片左右都包含
# print(series[0:3])

# 调整索引的时候数据也跟着调整
series = series.reindex(['d','a','c','b','e','f'])
'''
f     NaN
'''
print(series)

a     1
b     3
c     6
d    47
e    50
Name: movieId, dtype: int64
d    47.0
a     1.0
c     6.0
b     3.0
e    50.0
f     NaN
Name: movieId, dtype: float64

In [86]:
# 6. series的计算
# series1 = pd.Series([1,2,3,4],['A','B','D','E'])
# series2 = pd.Series([1,3,6,4],['A','C','E','F'])
# print(series1-series2)

# 同样也支持numpy的数组运算
sel = Series(data=[1,6,3,5], index = list('abcd'))
sel
# sel*2
# sel>3
# sel[sel>3]
np.square(sel)

a     1
b    36
c     9
d    25
dtype: int64

In [105]:
# 7. DataFrame的属性
import pandas as pd
from pandas import Series,DataFrame
import numpy as np

# dataframe常用属性
df = pd.read_csv('./file/ratings.csv')
df
# 获取行数和列数
# print(df.shape)
# 获取行索引
# print(df.index.tolist())
# 获取列索引
# print(df.columns.tolist())
# 获取数据的维度
# print(df.ndim)
# value属性也会以二维ndarray的形式返回DataFrame的数据
# print(df.values)
# 展示df的预览
# print(df.info())
# 显示头几行，默认显示5行
# print(df.head(2))
# 显示后几行
print(df.tail(1))

   userId  movieId  rating
4       1       50       5

In [192]:
# 8. DataFrame数据获取
df = pd.read_csv('./file/ratings.csv')
print(df)

# 获取一列
df['rating'] # 拿出的结果是series
df[['rating']] # 拿出的是DataFrame
# 获取多列
# df[['rating','movieId']]

# 获取一行 df[] 可以使用切片，可以使用布尔列表
df.index = list('abcde')
print(df['a':'a'])

# df[[True,False,True,False,True]]

# 将评分大于等于5的数据
# df[[i>=5 for i in df['rating']]]
# 简化
df[df['rating'] >= 5]

'''
df.loc[] 通过标签索引获取数据
df.iloc[] 通过位置索引获取数据
'''

# 一个值
df.loc['a','rating']

# 一行
df.loc['a',:]
df.loc['a',['movieId','rating']]
df.loc[['a','b'],['movieId','rating']]

# 选取rating==4的数据
df.loc[df['rating']==4, ['movieId']] # 获取=4的movieId这一列

df.iloc[[0,1,3],:]

   userId  movieId  rating
0       1        1       4
1       1        3       4
2       1        6       4
3       1       47       5
4       1       50       5
   userId  movieId  rating
a       1        1       4

   userId  movieId  rating
a       1        1       4
b       1        3       4
d       1       47       5

In [226]:
# 9. DataFrame修改index,colums
df1 = pd.DataFrame(np.arange(9).reshape(3,3),index=['bj','sh','gz'],columns=['a','b','c'])
# print(df1)

# 修改df1的index
df1.index = ['beijing','shanghai','guangzhou']
df1.columns = ['aa','bb','cc']
# print(df1)

# 从新改名

# def test_map(x):
#     if 'bb' in x:
#         return x+'_kkb'
#     return x

# df1.rename(columns=test_map)

# 字典映射改名
# df1.rename(index={'beijing':'bj','shanghai':'sh'})

# 列转化为索引
df1 = pd.DataFrame({'X':range(5),'Y':range(5),'S':list('abcde'),'Z':[1,1,2,2,2]})
print(df1)
result = df1.set_index('S',drop = False)
result.index.name = None
result

   X  Y  S  Z
0  0  0  a  1
1  1  1  b  1
2  2  2  c  2
3  3  3  d  2
4  4  4  e  2

   X  Y  S  Z
a  0  0  a  1
b  1  1  b  1
c  2  2  c  2
d  3  3  d  2
e  4  4  e  2

In [19]:
# 10. 练习
df = pd.read_csv('./file/BJ_tianqi.csv')
df

# 处理数据
df.loc[:,'最高温度'] = df['最高温度'].str.replace('℃','').astype('int32')
df.loc[:,'最低温度'] = df['最低温度'].str.replace('℃','').astype('int32')
df

# 补充:添加一列温差数据
df.loc[:,'温差'] = df['最高温度'] - df['最低温度']

# 补充:最高<30 并且最低>20
# df['最高温度']<30 df['最低温度'] >20
# result = df.loc[(df['最高温度']<30)&(df['最低温度']>20)]
# result

# 补充:基于最高温度和温差进行排序,最高温度降序，结果进行温差升序
# result = df.sort_values(by=['最高温度','温差'],ascending=[False,True]) 
# result

# 补充，最高温度大于30度，空气质量轻度污染的
# result = df.loc[(df['最高温度']>30)&(df['空气质量']=='轻度污染')]
# result

# 获取全年最高温度的前五名
# result = df.sort_values(by = '最高温度',ascending=False).head(5)
# result

            日期  最高温度  最低温度     天气   风向  风级  空气质量  温差
135  2019/5/16    32    17      晴  东南风  2级  轻度污染  15
136  2019/5/17    33    20   多云~阴  东南风  2级  轻度污染  13
168  2019/6/18    33    22    雷阵雨  西南风  2级  轻度污染  11
169  2019/6/19    33    22     多云  东南风  2级  轻度污染  11
170  2019/6/20    36    23   多云~晴  东南风  2级  轻度污染  13
201  2019/7/21    36    27   晴~多云  西南风  2级  轻度污染   9
202  2019/7/22    35    25  多云~中雨  西南风  2级  轻度污染  10
207  2019/7/27    36    27     多云  东南风  2级  轻度污染   9

In [58]:
# 练习，获取9月份数据（不能使用时间模块）
df = pd.read_csv('./file/BJ_tianqi.csv')
df

# 处理数据
## 获取字符串第6位为9的日期抽取出来名（列表生成式）

result = df[[i[5] == '9' for i in df['日期']]] # 第一种
## 
result = df[[i[0:6] == '2019/9' for i in df['日期']]] # 第二种
result

# 老师做法

df2 = pd.read_csv('./file/BJ_tianqi.csv')

# 第一种做法
df2.set_index('日期',inplace=True)
result = df2.loc['2019/9/1':'2019/9/30'] # 但是这个需要时间按顺序排列

# 第二种做法

df2.loc[[i.startswith('2019/9') for i in df2.index.tolist()],:]

# 如果可以用时间模块
df3 = pd.read_csv('./file/BJ_tianqi.csv')
df3['日期'] = pd.to_datetime(df3['日期'])
# df3.info() # 确定数据信息，包括类型
df3.set_index('日期',inplace=True)

# df3.loc['2019/09/01']

# df3.loc['2019/09']

#时间段截取

df3.loc['2019/09/01':'2019/09/07']

# 时间获取（拓展）
df4 = pd.read_csv('./file/BJ_tianqi.csv', parse_dates=['日期'])

df4['月份'] = df4['日期'].dt.month
df4['季度'] = df4['日期'].dt.to_period('Q')
df4

            日期 最高温度  最低温度    天气   风向  风级  空气质量  月份
0   2019-01-01   1℃  -10℃  晴~多云  西北风  1级     良   1
1   2019-01-02   1℃   -9℃    多云  东北风  1级     良   1
2   2019-01-03   2℃   -7℃     霾  东北风  1级  中度污染   1
3   2019-01-04   2℃   -7℃     晴  西北风  2级     优   1
4   2019-01-05   0℃   -8℃    多云  东北风  2级     优   1
..         ...  ...   ...   ...  ...  ..   ...  ..
360 2019-12-27   4℃   -6℃     晴  东北风  1级     良  12
361 2019-12-28   3℃   -7℃  晴~多云  东北风  1级     良  12
362 2019-12-29   5℃   -7℃  多云~晴  西北风  3级  轻度污染  12
363 2019-12-30  -5℃  -12℃     晴  西北风  4级     优  12
364 2019-12-31  -3℃  -10℃     晴  西北风  1级     优  12

[365 rows x 8 columns]

In [350]:
s = '2019/8/12'
s[0:5]

'2019/'